import {
  AppUser,
  Category,
  Product,
  StockMovement,
  Supplier,
} from "@/lib/types";

export const seedUsers: AppUser[] = [
  {
    id: "u1",
    name: "Budi Santoso",
    email: "admin@stokly.id",
    password: "admin123",
    role: "admin",
    initialsColor: "bg-amber-500",
  },
  {
    id: "u2",
    name: "Siti Aminah",
    email: "staff@stokly.id",
    password: "staff123",
    role: "staff",
    initialsColor: "bg-teal-500",
  },
  {
    id: "u3",
    name: "Joko Prasetyo",
    email: "joko@stokly.id",
    password: "staff123",
    role: "staff",
    initialsColor: "bg-violet-500",
  },
];

export const seedCategories: Category[] = [
  {
    id: "c1",
    name: "Elektronik",
    description: "Perangkat elektronik dan gadget",
  },
  {
    id: "c2",
    name: "Aksesoris Komputer",
    description: "Mouse, keyboard, dan periferal komputer",
  },
  {
    id: "c3",
    name: "Alat Tulis Kantor",
    description: "Perlengkapan tulis dan kebutuhan kantor",
  },
  {
    id: "c4",
    name: "Furnitur",
    description: "Meja, kursi, dan perabot kantor",
  },
  {
    id: "c5",
    name: "Peralatan Dapur",
    description: "Perlengkapan dapur dan rumah tangga",
  },
  {
    id: "c6",
    name: "Perlengkapan Jaringan",
    description: "Router, kabel, dan perangkat jaringan",
  },
];

export const seedSuppliers: Supplier[] = [
  {
    id: "s1",
    name: "PT Sumber Elektronik Jaya",
    contactName: "Hendra Wijaya",
    phone: "081234567801",
    email: "hendra@sumberelektronik.co.id",
    address: "Jl. Industri Raya No. 12, Tangerang",
  },
  {
    id: "s2",
    name: "CV Mitra Komputer Nusantara",
    contactName: "Rina Kartika",
    phone: "081234567802",
    email: "rina@mitrakomputer.co.id",
    address: "Jl. Pinangsia No. 45, Jakarta Barat",
  },
  {
    id: "s3",
    name: "Toko Pelangi ATK",
    contactName: "Agus Salim",
    phone: "081234567803",
    email: "agus@pelangiatk.co.id",
    address: "Jl. Veteran No. 8, Bandung",
  },
  {
    id: "s4",
    name: "UD Furnitur Makmur",
    contactName: "Dewi Lestari",
    phone: "081234567804",
    email: "dewi@furniturmakmur.co.id",
    address: "Jl. Raya Cikampek No. 99, Karawang",
  },
  {
    id: "s5",
    name: "PT Cipta Networking Indonesia",
    contactName: "Fajar Nugraha",
    phone: "081234567805",
    email: "fajar@ciptanetworking.co.id",
    address: "Jl. Gatot Subroto No. 23, Jakarta Selatan",
  },
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    sku: "ELK-001",
    name: "Speaker Bluetooth Mini 10W",
    categoryId: "c1",
    supplierId: "s1",
    unit: "pcs",
    costPrice: 120000,
    sellPrice: 185000,
    stock: 42,
    minStock: 15,
    description: "Speaker portabel dengan baterai tahan 8 jam",
    createdAt: "2025-11-02",
  },
  {
    id: "p2",
    sku: "ELK-002",
    name: "Power Bank 10000mAh",
    categoryId: "c1",
    supplierId: "s1",
    unit: "pcs",
    costPrice: 95000,
    sellPrice: 150000,
    stock: 8,
    minStock: 20,
    description: "Power bank fast charging dual port",
    createdAt: "2025-11-04",
  },
  {
    id: "p3",
    sku: "ELK-003",
    name: "Kabel Data USB-C 1.5m",
    categoryId: "c1",
    supplierId: "s1",
    unit: "pcs",
    costPrice: 18000,
    sellPrice: 35000,
    stock: 130,
    minStock: 40,
    createdAt: "2025-11-05",
  },
  {
    id: "p4",
    sku: "ELK-004",
    name: "Lampu Meja LED Dimmable",
    categoryId: "c1",
    supplierId: "s1",
    unit: "pcs",
    costPrice: 65000,
    sellPrice: 110000,
    stock: 0,
    minStock: 10,
    createdAt: "2025-11-08",
  },
  {
    id: "p5",
    sku: "AKS-001",
    name: "Mouse Wireless Silent Click",
    categoryId: "c2",
    supplierId: "s2",
    unit: "pcs",
    costPrice: 55000,
    sellPrice: 95000,
    stock: 64,
    minStock: 25,
    createdAt: "2025-11-01",
  },
  {
    id: "p6",
    sku: "AKS-002",
    name: "Keyboard Mechanical TKL",
    categoryId: "c2",
    supplierId: "s2",
    unit: "pcs",
    costPrice: 210000,
    sellPrice: 320000,
    stock: 17,
    minStock: 10,
    createdAt: "2025-11-03",
  },
  {
    id: "p7",
    sku: "AKS-003",
    name: "Mousepad Gaming XL",
    categoryId: "c2",
    supplierId: "s2",
    unit: "pcs",
    costPrice: 32000,
    sellPrice: 55000,
    stock: 5,
    minStock: 15,
    createdAt: "2025-11-06",
  },
  {
    id: "p8",
    sku: "AKS-004",
    name: "Webcam Full HD 1080p",
    categoryId: "c2",
    supplierId: "s2",
    unit: "pcs",
    costPrice: 175000,
    sellPrice: 265000,
    stock: 23,
    minStock: 12,
    createdAt: "2025-11-10",
  },
  {
    id: "p9",
    sku: "ATK-001",
    name: "Buku Tulis 58 Lembar (Lusin)",
    categoryId: "c3",
    supplierId: "s3",
    unit: "lusin",
    costPrice: 42000,
    sellPrice: 65000,
    stock: 88,
    minStock: 20,
    createdAt: "2025-10-28",
  },
  {
    id: "p10",
    sku: "ATK-002",
    name: "Pulpen Gel 0.5mm (Box isi 12)",
    categoryId: "c3",
    supplierId: "s3",
    unit: "box",
    costPrice: 28000,
    sellPrice: 48000,
    stock: 54,
    minStock: 20,
    createdAt: "2025-10-29",
  },
  {
    id: "p11",
    sku: "ATK-003",
    name: "Kertas A4 80gsm (Rim)",
    categoryId: "c3",
    supplierId: "s3",
    unit: "rim",
    costPrice: 48000,
    sellPrice: 62000,
    stock: 9,
    minStock: 25,
    createdAt: "2025-10-30",
  },
  {
    id: "p12",
    sku: "ATK-004",
    name: "Stapler Sedang + Isi",
    categoryId: "c3",
    supplierId: "s3",
    unit: "pcs",
    costPrice: 22000,
    sellPrice: 38000,
    stock: 31,
    minStock: 15,
    createdAt: "2025-11-02",
  },
  {
    id: "p13",
    sku: "ATK-005",
    name: "Spidol Whiteboard Set 4 Warna",
    categoryId: "c3",
    supplierId: "s3",
    unit: "set",
    costPrice: 26000,
    sellPrice: 42000,
    stock: 0,
    minStock: 12,
    createdAt: "2025-11-12",
  },
  {
    id: "p14",
    sku: "FUR-001",
    name: "Kursi Kantor Ergonomis",
    categoryId: "c4",
    supplierId: "s4",
    unit: "pcs",
    costPrice: 650000,
    sellPrice: 950000,
    stock: 12,
    minStock: 5,
    createdAt: "2025-10-15",
  },
  {
    id: "p15",
    sku: "FUR-002",
    name: "Meja Kerja Minimalis 120cm",
    categoryId: "c4",
    supplierId: "s4",
    unit: "pcs",
    costPrice: 480000,
    sellPrice: 720000,
    stock: 4,
    minStock: 5,
    createdAt: "2025-10-18",
  },
  {
    id: "p16",
    sku: "FUR-003",
    name: "Lemari Arsip 2 Pintu",
    categoryId: "c4",
    supplierId: "s4",
    unit: "pcs",
    costPrice: 890000,
    sellPrice: 1250000,
    stock: 6,
    minStock: 3,
    createdAt: "2025-10-20",
  },
  {
    id: "p17",
    sku: "DPR-001",
    name: "Toples Kaca Set 3 Ukuran",
    categoryId: "c5",
    supplierId: "s4",
    unit: "set",
    costPrice: 38000,
    sellPrice: 65000,
    stock: 27,
    minStock: 10,
    createdAt: "2025-11-01",
  },
  {
    id: "p18",
    sku: "DPR-002",
    name: "Termos Air Panas 1.8L",
    categoryId: "c5",
    supplierId: "s4",
    unit: "pcs",
    costPrice: 55000,
    sellPrice: 89000,
    stock: 19,
    minStock: 10,
    createdAt: "2025-11-03",
  },
  {
    id: "p19",
    sku: "DPR-003",
    name: "Rak Piring Stainless 2 Susun",
    categoryId: "c5",
    supplierId: "s4",
    unit: "pcs",
    costPrice: 95000,
    sellPrice: 145000,
    stock: 3,
    minStock: 8,
    createdAt: "2025-11-07",
  },
  {
    id: "p20",
    sku: "NET-001",
    name: "Router WiFi AC1200 Dual Band",
    categoryId: "c6",
    supplierId: "s5",
    unit: "pcs",
    costPrice: 245000,
    sellPrice: 375000,
    stock: 14,
    minStock: 8,
    createdAt: "2025-10-25",
  },
  {
    id: "p21",
    sku: "NET-002",
    name: "Kabel LAN Cat6 (Roll 100m)",
    categoryId: "c6",
    supplierId: "s5",
    unit: "roll",
    costPrice: 320000,
    sellPrice: 460000,
    stock: 7,
    minStock: 5,
    createdAt: "2025-10-27",
  },
  {
    id: "p22",
    sku: "NET-003",
    name: "Switch Hub 8 Port Gigabit",
    categoryId: "c6",
    supplierId: "s5",
    unit: "pcs",
    costPrice: 175000,
    sellPrice: 265000,
    stock: 21,
    minStock: 10,
    createdAt: "2025-11-04",
  },
  {
    id: "p23",
    sku: "NET-004",
    name: "Access Point Outdoor",
    categoryId: "c6",
    supplierId: "s5",
    unit: "pcs",
    costPrice: 410000,
    sellPrice: 595000,
    stock: 2,
    minStock: 5,
    createdAt: "2025-11-09",
  },
  {
    id: "p24",
    sku: "ELK-005",
    name: "Earphone Kabel In-Ear",
    categoryId: "c1",
    supplierId: "s1",
    unit: "pcs",
    costPrice: 28000,
    sellPrice: 49000,
    stock: 76,
    minStock: 25,
    createdAt: "2025-11-11",
  },
];

function isoDaysAgo(days: number) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(9 + (days % 7), 15, 0, 0);
  return d.toISOString();
}

const movementSeed: {
  productId: string;
  type: "in" | "out";
  quantity: number;
  daysAgo: number;
  note: string;
  reference: string;
  by: string;
}[] = [
  { productId: "p1", type: "in", quantity: 50, daysAgo: 20, note: "Restock awal bulan", reference: "PO-2041", by: "Budi Santoso" },
  { productId: "p2", type: "in", quantity: 30, daysAgo: 19, note: "Restock dari supplier", reference: "PO-2042", by: "Budi Santoso" },
  { productId: "p5", type: "in", quantity: 80, daysAgo: 19, note: "Restock rutin", reference: "PO-2043", by: "Siti Aminah" },
  { productId: "p9", type: "in", quantity: 100, daysAgo: 18, note: "Restock ATK bulanan", reference: "PO-2044", by: "Siti Aminah" },
  { productId: "p14", type: "in", quantity: 15, daysAgo: 17, note: "Pengadaan furnitur baru", reference: "PO-2045", by: "Budi Santoso" },
  { productId: "p3", type: "out", quantity: 25, daysAgo: 17, note: "Penjualan toko", reference: "SO-3011", by: "Joko Prasetyo" },
  { productId: "p1", type: "out", quantity: 12, daysAgo: 16, note: "Penjualan online", reference: "SO-3012", by: "Joko Prasetyo" },
  { productId: "p2", type: "out", quantity: 18, daysAgo: 16, note: "Penjualan toko", reference: "SO-3013", by: "Joko Prasetyo" },
  { productId: "p10", type: "in", quantity: 60, daysAgo: 15, note: "Restock pulpen", reference: "PO-2046", by: "Siti Aminah" },
  { productId: "p20", type: "in", quantity: 20, daysAgo: 15, note: "Restock perangkat jaringan", reference: "PO-2047", by: "Budi Santoso" },
  { productId: "p6", type: "out", quantity: 8, daysAgo: 14, note: "Penjualan toko", reference: "SO-3014", by: "Joko Prasetyo" },
  { productId: "p5", type: "out", quantity: 22, daysAgo: 14, note: "Penjualan online", reference: "SO-3015", by: "Joko Prasetyo" },
  { productId: "p11", type: "in", quantity: 40, daysAgo: 13, note: "Restock kertas A4", reference: "PO-2048", by: "Siti Aminah" },
  { productId: "p2", type: "out", quantity: 14, daysAgo: 13, note: "Penjualan toko", reference: "SO-3016", by: "Joko Prasetyo" },
  { productId: "p7", type: "out", quantity: 20, daysAgo: 12, note: "Penjualan online", reference: "SO-3017", by: "Joko Prasetyo" },
  { productId: "p21", type: "in", quantity: 12, daysAgo: 12, note: "Restock kabel LAN", reference: "PO-2049", by: "Budi Santoso" },
  { productId: "p3", type: "out", quantity: 30, daysAgo: 11, note: "Penjualan grosir", reference: "SO-3018", by: "Joko Prasetyo" },
  { productId: "p17", type: "in", quantity: 25, daysAgo: 11, note: "Restock peralatan dapur", reference: "PO-2050", by: "Siti Aminah" },
  { productId: "p4", type: "out", quantity: 10, daysAgo: 10, note: "Penjualan toko", reference: "SO-3019", by: "Joko Prasetyo" },
  { productId: "p13", type: "out", quantity: 12, daysAgo: 10, note: "Penjualan toko", reference: "SO-3020", by: "Joko Prasetyo" },
  { productId: "p8", type: "in", quantity: 18, daysAgo: 9, note: "Restock webcam", reference: "PO-2051", by: "Budi Santoso" },
  { productId: "p19", type: "out", quantity: 9, daysAgo: 9, note: "Penjualan toko", reference: "SO-3021", by: "Joko Prasetyo" },
  { productId: "p23", type: "out", quantity: 6, daysAgo: 8, note: "Penjualan proyek", reference: "SO-3022", by: "Joko Prasetyo" },
  { productId: "p1", type: "out", quantity: 9, daysAgo: 8, note: "Penjualan online", reference: "SO-3023", by: "Joko Prasetyo" },
  { productId: "p15", type: "out", quantity: 3, daysAgo: 7, note: "Penjualan toko", reference: "SO-3024", by: "Joko Prasetyo" },
  { productId: "p9", type: "out", quantity: 18, daysAgo: 7, note: "Penjualan grosir", reference: "SO-3025", by: "Joko Prasetyo" },
  { productId: "p24", type: "in", quantity: 90, daysAgo: 6, note: "Restock earphone", reference: "PO-2052", by: "Siti Aminah" },
  { productId: "p6", type: "out", quantity: 5, daysAgo: 6, note: "Penjualan toko", reference: "SO-3026", by: "Joko Prasetyo" },
  { productId: "p22", type: "out", quantity: 7, daysAgo: 5, note: "Penjualan online", reference: "SO-3027", by: "Joko Prasetyo" },
  { productId: "p3", type: "out", quantity: 20, daysAgo: 5, note: "Penjualan toko", reference: "SO-3028", by: "Joko Prasetyo" },
  { productId: "p12", type: "out", quantity: 6, daysAgo: 4, note: "Penjualan toko", reference: "SO-3029", by: "Joko Prasetyo" },
  { productId: "p18", type: "out", quantity: 5, daysAgo: 4, note: "Penjualan online", reference: "SO-3030", by: "Joko Prasetyo" },
  { productId: "p2", type: "in", quantity: 25, daysAgo: 3, note: "Restock darurat", reference: "PO-2053", by: "Budi Santoso" },
  { productId: "p5", type: "out", quantity: 16, daysAgo: 3, note: "Penjualan toko", reference: "SO-3031", by: "Joko Prasetyo" },
  { productId: "p10", type: "out", quantity: 14, daysAgo: 2, note: "Penjualan toko", reference: "SO-3032", by: "Joko Prasetyo" },
  { productId: "p1", type: "out", quantity: 7, daysAgo: 2, note: "Penjualan online", reference: "SO-3033", by: "Joko Prasetyo" },
  { productId: "p24", type: "out", quantity: 22, daysAgo: 1, note: "Penjualan grosir", reference: "SO-3034", by: "Joko Prasetyo" },
  { productId: "p20", type: "out", quantity: 4, daysAgo: 1, note: "Penjualan toko", reference: "SO-3035", by: "Joko Prasetyo" },
  { productId: "p3", type: "in", quantity: 50, daysAgo: 0, note: "Restock mingguan", reference: "PO-2054", by: "Siti Aminah" },
  { productId: "p8", type: "out", quantity: 3, daysAgo: 0, note: "Penjualan toko", reference: "SO-3036", by: "Joko Prasetyo" },
];

export const seedMovements: StockMovement[] = movementSeed.map((m, idx) => ({
  id: `m${idx + 1}`,
  productId: m.productId,
  type: m.type,
  quantity: m.quantity,
  date: isoDaysAgo(m.daysAgo),
  note: m.note,
  reference: m.reference,
  by: m.by,
}));
